"""short-horizon-v1 problem variant bp_sh_e_rand (generated by experiments/short-horizon-v1/make_problems.py).

Online bin packing with FunSearch's interface and the item generator of problems/bin_packing_online.
An instance is one or more independent streams; bins and the candidate module's state start fresh for
every stream (the trusted DRIVER re-executes the module), as if each stream ran in its own process.
Score of a stream instance: sum of Martello-Toth L2 bounds / sum of bins used.
Score of a suite instance: 1 - 1e-8 x (streams where the rule uses more bins than best fit).
"""
import hashlib
import json
import math
import random
from functools import lru_cache
from pathlib import Path

FUNCTION = "priority"
CAPACITY = 100
_SALT = "bin_packing_online/v1/7f3c9e"     # the generator of problems/bin_packing_online
PUBLIC = [{"name": "instance 1", "streams": [[85500, 5000]]}, {"name": "instance 2", "streams": [[85501, 5000]]}, {"name": "instance 3", "suite": "suite.json"}]
HIDDEN = [{"name": "hidden 1", "streams": [[85900, 5000]]}, {"name": "hidden 2", "streams": [[85901, 5000]]}]
TIMEOUT_S = 60

DRIVER = r"""
import importlib.util
import numpy as np

def drive(priority, header, next_input, emit):
    cap = header["capacity"]
    path = priority.__globals__.get("__file__")
    name = priority.__name__
    for k, n in enumerate(header["streams"]):
        if k > 0:   # fresh module state for every stream
            spec = importlib.util.spec_from_file_location("candidate", path)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            priority = getattr(mod, name)
        bins = np.full(n, cap, dtype=np.int64)
        for _ in range(n):
            item = next_input()
            if item is None:
                return
            valid = np.nonzero((bins - item) >= 0)[0]
            scores = np.asarray(priority(item, bins[valid]), dtype=np.float64)
            if scores.shape != valid.shape:
                raise ValueError(f"priority returned shape {scores.shape}; expected {valid.shape}")
            if np.isnan(scores).any():
                raise ValueError("priority returned NaN")
            chosen = int(valid[np.argmax(scores)])
            bins[chosen] -= item
            emit(chosen)
"""


@lru_cache(maxsize=4096)
def items_for(seed: int, n: int) -> tuple:
    digest = hashlib.sha256(f"{_SALT}:{seed}".encode()).digest()
    rng = random.Random(int.from_bytes(digest[:8], "big"))
    return tuple(min(CAPACITY, max(1, int(rng.weibullvariate(45.0, 3.0)))) for _ in range(n))


def l2_bound(items, capacity=CAPACITY) -> int:
    """Martello-Toth (1990) L2 lower bound for integer item sizes."""
    counts = [0] * (capacity + 1)
    for x in items:
        counts[x] += 1
    best = math.ceil(sum(items) / capacity)
    for k in range(0, capacity // 2 + 1):
        n1 = sum(counts[capacity - k + 1:])
        j2 = range(capacity // 2 + 1, capacity - k + 1)
        n2 = sum(counts[s] for s in j2)
        s2 = sum(s * counts[s] for s in j2)
        s3 = sum(s * counts[s] for s in range(max(k, 1), capacity // 2 + 1))
        best = max(best, n1 + n2 + max(0, math.ceil((s3 - (n2 * capacity - s2)) / capacity)))
    return best


@lru_cache(maxsize=8)
def _suite(name):
    return tuple(tuple(s) for s in json.loads((Path(__file__).parent / name).read_text())["streams"])


def streams(instance):
    if "suite" in instance:
        return [list(s) for s in _suite(instance["suite"])]
    return [list(items_for(seed, n)) for seed, n in instance["streams"]]


def best_fit_bins(items, capacity=CAPACITY):
    gaps = []
    for x in items:
        fits = [g for g in gaps if g >= x]
        if fits:
            g = min(fits)
            gaps[gaps.index(g)] = g - x
        else:
            gaps.append(capacity - x)
    return len(gaps)


def online(instance):
    ss = streams(instance)
    return {"capacity": CAPACITY, "streams": [len(s) for s in ss]}, [x for s in ss for x in s]


def label(instance):
    ss = streams(instance)
    lens = sorted(set(len(s) for s in ss))
    if "suite" in instance:
        return f"{instance['name']} ({len(ss)} short streams of {lens[0]}-{lens[-1]} items)"
    total = sum(l2_bound(s) for s in ss)
    shape = f"{len(ss)} streams of {lens[0]} items" if len(ss) > 1 else f"{lens[0]} items"
    return f"{instance['name']} ({shape}, lower bound {total} bins)"


def best_known(instance):
    return None


def _bins_per_stream(construction, ss):
    if not isinstance(construction, list) or len(construction) != sum(len(s) for s in ss):
        raise ValueError("expected one bin index per item")
    out, k = [], 0
    for s in ss:
        load = {}
        for x in s:
            b = construction[k]
            k += 1
            if not isinstance(b, int) or isinstance(b, bool) or not 0 <= b < len(s):
                raise ValueError("invalid bin index")
            load[b] = load.get(b, 0) + x
            if load[b] > CAPACITY:
                raise ValueError("bin over capacity")
        out.append(len(load))
    return out


def check(construction, instance):
    ss = streams(instance)
    try:
        used = _bins_per_stream(construction, ss)
    except ValueError as e:
        return {"valid": False, "score": None, "reason": str(e)}
    if "suite" in instance:
        losses = sum(u > best_fit_bins(s) for u, s in zip(used, ss))
        return {"valid": True, "score": 1.0 - 1e-8 * losses, "reason": f"{losses} streams worse than best fit"}
    return {"valid": True, "score": sum(l2_bound(s) for s in ss) / sum(used), "reason": f"{sum(used)} bins"}
